-- rotations/defaults/AllSpecs.lua
-- This file is auto-generated by the build pipeline. 
-- It allows the addon to function offline with zero configuration.

local data = {}

-- Placeholder for DEATHKNIGHT_251 to test the fallback
data["DEATHKNIGHT_251"] = {
  Midnight = {
    type="Priority",
    st = {
      { command="/cast Pillar of Frost", conditions="can_cast:Pillar of Frost" },
      { command="/cast Obliterate", conditions="can_cast:Obliterate" },
      { command="/cast Frost Strike", conditions="can_cast:Frost Strike" },
    },
    aoe = {
      { command="/cast Remorseless Winter", conditions="can_cast:Remorseless Winter" },
      { command="/cast Howling Blast", conditions="can_cast:Howling Blast" },
    },
    steps = {}
  },
  MythicPlus = { Safe = { steps = { {command="/cast Obliterate"}, {command="/cast Frost Strike"} } } },
  Raid      = { Safe = { steps = { {command="/cast Obliterate"}, {command="/cast Frost Strike"} } } },
}

return data
