#!/bin/bash

################################################################################
# Goblin Superproject - MASTER CREATION SCRIPT (ULTRA-SAFE VERSION)
# Logging: yes
# Success banner: yes
################################################################################

set -euo pipefail

BASE_DIR="$HOME/Documents/goblin-clean"
SCRIPTS_DIR="$BASE_DIR/scripts"
LOGFILE="$BASE_DIR/create_goblin_superproject.log"

# ensure logfile exists
mkdir -p "$BASE_DIR"
touch "$LOGFILE"

log() {
    printf "%s\n" "$1" | tee -a "$LOGFILE"
}

log ""
log "========================================================"
log "     Goblin Superproject Builder (Ultra-Safe Edition)   "
log "========================================================"
log ""

################################################################################
# STEP 1 — CREATE BASE DIRECTORY
################################################################################

log "[1/10] Ensuring directory exists: $BASE_DIR"
mkdir -p "$BASE_DIR"
mkdir -p "$SCRIPTS_DIR"
log "✔ Base directory ready"

################################################################################
# HELPER WRITER (SAFE FILE CREATOR)
################################################################################

write_file() {
    local path="$1"
    shift
    {
        for line in "$@"; do
            printf "%s\n" "$line"
        done
    } > "$path"
    log "  ✔ Created file: $path"
}

################################################################################
# STEP 2 — PYTHON 3.11+ DETECTION
################################################################################

log "[2/10] Checking Python version ..."

if command -v python3.11 >/dev/null 2>&1; then
    PYTHON_BIN=$(command -v python3.11)
elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN=$(command -v python3)
else
    log "❌ ERROR: Python 3.11+ not found."
    exit 1
fi

log "✔ Using Python: $PYTHON_BIN"

################################################################################
# STEP 3 — CREATE VENV
################################################################################

log "[3/10] Creating Python virtual environment ..."
cd "$BASE_DIR"
$PYTHON_BIN -m venv venv
log "✔ Virtual environment created"

source venv/bin/activate
log "✔ Virtual environment activated"

################################################################################
# STEP 4 — REQUIREMENTS INSTALL
################################################################################

log "[4/10] Installing requirements ..."

write_file "$BASE_DIR/requirements.txt" \
"fastapi" \
"uvicorn[standard]" \
"pydantic" \
"python-dotenv" \
"requests" \
"pandas" \
"numpy" \
"scikit-learn" \
"schedule" \
"loguru"

pip install --upgrade pip | tee -a "$LOGFILE"
pip install -r "$BASE_DIR/requirements.txt" | tee -a "$LOGFILE"

log "✔ Requirements installed"

################################################################################
# STEP 5 — RUN SUBSYSTEM SCRIPTS
################################################################################

log "[5/10] Running subsystem setup scripts ..."

bash "$SCRIPTS_DIR/setup_backend.sh"   | tee -a "$LOGFILE"
bash "$SCRIPTS_DIR/setup_agents.sh"    | tee -a "$LOGFILE"
bash "$SCRIPTS_DIR/setup_ml.sh"        | tee -a "$LOGFILE"
bash "$SCRIPTS_DIR/setup_ops.sh"       | tee -a "$LOGFILE"
bash "$SCRIPTS_DIR/setup_ui.sh"        | tee -a "$LOGFILE"

log "✔ All subsystems completed"

################################################################################
# STEP 6 — ROOT-LEVEL FILES
################################################################################

log "[6/10] Writing root-level files ..."

write_file "$BASE_DIR/.gitignore" \
"venv/" \
"__pycache__/" \
"*.pyc" \
"*.pkl" \
"*.log" \
".env"

write_file "$BASE_DIR/.env.sample" \
"# Goblin Environment Variables" \
"API_KEY=\"your_api_key_here\"" \
"LOG_LEVEL=\"INFO\""

write_file "$BASE_DIR/README.md" \
"# Goblin Superproject" \
"Autogenerated by the Goblin build script." \
"" \
"This includes backend, agents, ML, ops, and UI stubs."

log "✔ Root-level files created"

################################################################################
# STEP 7 — GIT INIT
################################################################################

log "[7/10] Initializing Git repository ..."

cd "$BASE_DIR"
git init | tee -a "$LOGFILE"

git remote remove origin 2>/dev/null || true
git remote add origin git@github.com:jsgrayson/goblin-clean.git

git add . | tee -a "$LOGFILE"
git commit -m "Initial Goblin Superproject scaffold (auto-generated)" | tee -a "$LOGFILE"

log "✔ Git initialized"

################################################################################
# STEP 8 — SUMMARY
################################################################################

log "[8/10] Build Summary"
log "  Base directory: $BASE_DIR"
log "  Scripts dir:    $SCRIPTS_DIR"
log "  Log file:       $LOGFILE"

################################################################################
# STEP 9 — SUCCESS BANNER
################################################################################

log ""
log "========================================================"
log "       🎉 GOBLIN SUPERPROJECT CREATED SUCCESSFULLY! 🎉"
log "========================================================"
log ""

log "To activate your environment:"
log "  source ~/Documents/goblin-clean/venv/bin/activate"
log ""
log "To push to GitHub:"
log "  cd ~/Documents/goblin-clean"
log "  git push -u origin main"
log ""

################################################################################
# STEP 10 — EXIT CLEANLY
################################################################################

exit 0

