-- data/Classes/ALL.lua
-- Offline-only rotations tuned primarily for Delves/Open World (fast pulls, high safety).
SkillWeaver = SkillWeaver or {}
local SW = SkillWeaver

local data = {}

local function S(cmd) return { command = cmd } end

local function mkRotation(stSteps, aoeSteps, intMacro, utilMacro, healSteps)
  return {
    ST   = { steps = stSteps },
    AOE  = { steps = aoeSteps and #aoeSteps > 0 and aoeSteps or stSteps },
    INT  = { macro = intMacro or "" },
    UTIL = { macro = utilMacro or "" },
    HEAL = healSteps and { steps = healSteps } or nil,
  }
end

local function mkProfiles(bal, hp, safe)
  return { Balanced = bal, HighPerformance = hp or bal, Safe = safe or bal }
end

local function mkAllModes(profiles, pvpProfiles)
  return { Delves = profiles, OpenWorld = profiles, MythicPlus = profiles, Raid = profiles, PvP = pvpProfiles or profiles }
end

-- DEATHKNIGHT_250
data["DEATHKNIGHT_250"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Dancing Rune Weapon"), S("/cast Marrowrend"), S("/cast Death Strike"), S("/cast Heart Strike"), S("/cast Blood Boil"), S("/cast Death and Decay") }, { S("/cast Dancing Rune Weapon"), S("/cast Death and Decay"), S("/cast Blood Boil"), S("/cast Heart Strike"), S("/cast Death Strike"), S("/cast Marrowrend") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil), mkRotation({ S("/cast [mod:alt] Dancing Rune Weapon"), S("/cast Marrowrend"), S("/cast Death Strike"), S("/cast Heart Strike"), S("/cast Blood Boil"), S("/cast Death and Decay") }, { S("/cast [mod:alt] Dancing Rune Weapon"), S("/cast Death and Decay"), S("/cast Blood Boil"), S("/cast Heart Strike"), S("/cast Death Strike"), S("/cast Marrowrend") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil), mkRotation({ S("/cast Marrowrend"), S("/cast Death Strike"), S("/cast Heart Strike"), S("/cast Blood Boil"), S("/cast Death and Decay") }, { S("/cast Death and Decay"), S("/cast Blood Boil"), S("/cast Heart Strike"), S("/cast Death Strike"), S("/cast Marrowrend") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil)))

-- DEATHKNIGHT_251
data["DEATHKNIGHT_251"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Pillar of Frost"), S("/cast Obliterate"), S("/cast Frost Strike"), S("/cast Howling Blast"), S("/cast Remorseless Winter") }, { S("/cast Pillar of Frost"), S("/cast Remorseless Winter"), S("/cast Howling Blast"), S("/cast Frost Strike"), S("/cast Obliterate") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil), mkRotation({ S("/cast [mod:alt] Pillar of Frost"), S("/cast Obliterate"), S("/cast Frost Strike"), S("/cast Howling Blast"), S("/cast Remorseless Winter") }, { S("/cast [mod:alt] Pillar of Frost"), S("/cast Remorseless Winter"), S("/cast Howling Blast"), S("/cast Frost Strike"), S("/cast Obliterate") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil), mkRotation({ S("/cast Obliterate"), S("/cast Frost Strike"), S("/cast Howling Blast"), S("/cast Remorseless Winter") }, { S("/cast Remorseless Winter"), S("/cast Howling Blast"), S("/cast Frost Strike"), S("/cast Obliterate") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil)))

-- DEATHKNIGHT_252
data["DEATHKNIGHT_252"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Army of the Dead"), S("/cast Dark Transformation"), S("/cast Outbreak"), S("/cast Apocalypse"), S("/cast Festering Strike"), S("/cast Scourge Strike"), S("/cast Death Coil") }, { S("/cast Army of the Dead"), S("/cast Dark Transformation"), S("/cast Outbreak"), S("/cast Death and Decay"), S("/cast Epidemic"), S("/cast Festering Strike"), S("/cast Scourge Strike") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil), mkRotation({ S("/cast [mod:alt] Army of the Dead"), S("/cast Dark Transformation"), S("/cast Outbreak"), S("/cast Apocalypse"), S("/cast Festering Strike"), S("/cast Scourge Strike"), S("/cast Death Coil") }, { S("/cast [mod:alt] Army of the Dead"), S("/cast Dark Transformation"), S("/cast Outbreak"), S("/cast Death and Decay"), S("/cast Epidemic"), S("/cast Festering Strike"), S("/cast Scourge Strike") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil), mkRotation({ S("/cast Dark Transformation"), S("/cast Outbreak"), S("/cast Apocalypse"), S("/cast Festering Strike"), S("/cast Scourge Strike"), S("/cast Death Coil") }, { S("/cast Dark Transformation"), S("/cast Outbreak"), S("/cast Death and Decay"), S("/cast Epidemic"), S("/cast Festering Strike"), S("/cast Scourge Strike") }, "/cast [harm] Mind Freeze\n", "/cast Icebound Fortitude\n/cast Vampiric Blood\n", nil)))

-- DEMONHUNTER_577
data["DEMONHUNTER_577"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Metamorphosis"), S("/cast Eye Beam"), S("/cast Blade Dance"), S("/cast Chaos Strike"), S("/cast Demon's Bite") }, { S("/cast Metamorphosis"), S("/cast Eye Beam"), S("/cast Blade Dance"), S("/cast Immolation Aura"), S("/cast Chaos Strike"), S("/cast Throw Glaive") }, "/cast [harm] Disrupt\n", "/cast Blur\n/cast Darkness\n", nil), mkRotation({ S("/cast [mod:alt] Metamorphosis"), S("/cast Eye Beam"), S("/cast Blade Dance"), S("/cast Chaos Strike"), S("/cast Demon's Bite") }, { S("/cast [mod:alt] Metamorphosis"), S("/cast Eye Beam"), S("/cast Blade Dance"), S("/cast Immolation Aura"), S("/cast Chaos Strike"), S("/cast Throw Glaive") }, "/cast [harm] Disrupt\n", "/cast Blur\n/cast Darkness\n", nil), mkRotation({ S("/cast Eye Beam"), S("/cast Blade Dance"), S("/cast Chaos Strike"), S("/cast Demon's Bite") }, { S("/cast Eye Beam"), S("/cast Blade Dance"), S("/cast Immolation Aura"), S("/cast Chaos Strike"), S("/cast Throw Glaive") }, "/cast [harm] Disrupt\n", "/cast Blur\n/cast Darkness\n", nil)))

-- DEMONHUNTER_581
data["DEMONHUNTER_581"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Metamorphosis"), S("/cast Demon Spikes"), S("/cast Spirit Bomb"), S("/cast Soul Cleave"), S("/cast Shear"), S("/cast Immolation Aura") }, { S("/cast Metamorphosis"), S("/cast Demon Spikes"), S("/cast Immolation Aura"), S("/cast Spirit Bomb"), S("/cast Soul Cleave"), S("/cast Sigil of Flame"), S("/cast Shear") }, "/cast [harm] Disrupt\n", "/cast Blur\n/cast Darkness\n", nil), mkRotation({ S("/cast [mod:alt] Metamorphosis"), S("/cast Demon Spikes"), S("/cast Spirit Bomb"), S("/cast Soul Cleave"), S("/cast Shear"), S("/cast Immolation Aura") }, { S("/cast [mod:alt] Metamorphosis"), S("/cast Demon Spikes"), S("/cast Immolation Aura"), S("/cast Spirit Bomb"), S("/cast Soul Cleave"), S("/cast Sigil of Flame"), S("/cast Shear") }, "/cast [harm] Disrupt\n", "/cast Blur\n/cast Darkness\n", nil), mkRotation({ S("/cast Demon Spikes"), S("/cast Spirit Bomb"), S("/cast Soul Cleave"), S("/cast Shear"), S("/cast Immolation Aura") }, { S("/cast Demon Spikes"), S("/cast Immolation Aura"), S("/cast Spirit Bomb"), S("/cast Soul Cleave"), S("/cast Sigil of Flame"), S("/cast Shear") }, "/cast [harm] Disrupt\n", "/cast Blur\n/cast Darkness\n", nil)))

-- DRUID_102
data["DRUID_102"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Celestial Alignment"), S("/cast Moonfire"), S("/cast Sunfire"), S("/cast Starsurge"), S("/cast Wrath"), S("/cast Starfire") }, { S("/cast Celestial Alignment"), S("/cast Sunfire"), S("/cast Moonfire"), S("/cast Starfall"), S("/cast Starfire"), S("/cast Wrath") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil), mkRotation({ S("/cast [mod:alt] Celestial Alignment"), S("/cast Moonfire"), S("/cast Sunfire"), S("/cast Starsurge"), S("/cast Wrath"), S("/cast Starfire") }, { S("/cast [mod:alt] Celestial Alignment"), S("/cast Sunfire"), S("/cast Moonfire"), S("/cast Starfall"), S("/cast Starfire"), S("/cast Wrath") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil), mkRotation({ S("/cast Moonfire"), S("/cast Sunfire"), S("/cast Starsurge"), S("/cast Wrath"), S("/cast Starfire") }, { S("/cast Sunfire"), S("/cast Moonfire"), S("/cast Starfall"), S("/cast Starfire"), S("/cast Wrath") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil)))

-- DRUID_103
data["DRUID_103"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Berserk"), S("/cast Rake"), S("/cast Rip"), S("/cast Ferocious Bite"), S("/cast Shred") }, { S("/cast Berserk"), S("/cast Thrash"), S("/cast Swipe"), S("/cast Rake"), S("/cast Rip"), S("/cast Ferocious Bite") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil), mkRotation({ S("/cast [mod:alt] Berserk"), S("/cast Rake"), S("/cast Rip"), S("/cast Ferocious Bite"), S("/cast Shred") }, { S("/cast [mod:alt] Berserk"), S("/cast Thrash"), S("/cast Swipe"), S("/cast Rake"), S("/cast Rip"), S("/cast Ferocious Bite") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil), mkRotation({ S("/cast Rake"), S("/cast Rip"), S("/cast Ferocious Bite"), S("/cast Shred") }, { S("/cast Thrash"), S("/cast Swipe"), S("/cast Rake"), S("/cast Rip"), S("/cast Ferocious Bite") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil)))

-- DRUID_104
data["DRUID_104"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Berserk"), S("/cast Ironfur"), S("/cast Thrash"), S("/cast Mangle"), S("/cast Moonfire"), S("/cast Maul") }, { S("/cast Berserk"), S("/cast Ironfur"), S("/cast Thrash"), S("/cast Swipe"), S("/cast Moonfire"), S("/cast Mangle") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil), mkRotation({ S("/cast [mod:alt] Berserk"), S("/cast Ironfur"), S("/cast Thrash"), S("/cast Mangle"), S("/cast Moonfire"), S("/cast Maul") }, { S("/cast [mod:alt] Berserk"), S("/cast Ironfur"), S("/cast Thrash"), S("/cast Swipe"), S("/cast Moonfire"), S("/cast Mangle") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil), mkRotation({ S("/cast Ironfur"), S("/cast Thrash"), S("/cast Mangle"), S("/cast Moonfire"), S("/cast Maul") }, { S("/cast Ironfur"), S("/cast Thrash"), S("/cast Swipe"), S("/cast Moonfire"), S("/cast Mangle") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n", nil)))

-- DRUID_105
data["DRUID_105"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Swiftmend"), S("/cast Rejuvenation"), S("/cast Lifebloom"), S("/cast Regrowth"), S("/cast Wild Growth") }, { S("/cast Tranquility"), S("/cast Wild Growth"), S("/cast Rejuvenation"), S("/cast Regrowth"), S("/cast Swiftmend") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n/cast Ironbark\n", { S("/cast Rejuvenation"), S("/cast Regrowth"), S("/cast Lifebloom"), S("/cast Swiftmend"), S("/cast Wild Growth") }), mkRotation({ S("/cast [mod:alt] Swiftmend"), S("/cast Rejuvenation"), S("/cast Lifebloom"), S("/cast Regrowth"), S("/cast Wild Growth") }, { S("/cast [mod:alt] Tranquility"), S("/cast Wild Growth"), S("/cast Rejuvenation"), S("/cast Regrowth"), S("/cast Swiftmend") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n/cast Ironbark\n", { S("/cast Rejuvenation"), S("/cast Regrowth"), S("/cast Lifebloom"), S("/cast Swiftmend"), S("/cast Wild Growth") }), mkRotation({ S("/cast Swiftmend"), S("/cast Rejuvenation"), S("/cast Lifebloom"), S("/cast Regrowth"), S("/cast Wild Growth") }, { S("/cast Wild Growth"), S("/cast Rejuvenation"), S("/cast Regrowth"), S("/cast Swiftmend") }, "/cast [harm] Skull Bash\n", "/cast Barkskin\n/cast Ironbark\n", { S("/cast Rejuvenation"), S("/cast Regrowth"), S("/cast Lifebloom"), S("/cast Swiftmend"), S("/cast Wild Growth") })))

-- EVOKER_1467
data["EVOKER_1467"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Breath of Eons"), S("/cast Fire Breath"), S("/cast Living Flame"), S("/cast Disintegrate"), S("/cast Azure Strike") }, { S("/cast Breath of Eons"), S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Pyre"), S("/cast Azure Strike") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n", nil), mkRotation({ S("/cast [mod:alt] Breath of Eons"), S("/cast Fire Breath"), S("/cast Living Flame"), S("/cast Disintegrate"), S("/cast Azure Strike") }, { S("/cast [mod:alt] Breath of Eons"), S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Pyre"), S("/cast Azure Strike") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n", nil), mkRotation({ S("/cast Fire Breath"), S("/cast Living Flame"), S("/cast Disintegrate"), S("/cast Azure Strike") }, { S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Pyre"), S("/cast Azure Strike") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n", nil)))

-- EVOKER_1468
data["EVOKER_1468"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Dragonrage"), S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Disintegrate"), S("/cast Living Flame") }, { S("/cast Dragonrage"), S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Pyre"), S("/cast Living Flame") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n", nil), mkRotation({ S("/cast [mod:alt] Dragonrage"), S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Disintegrate"), S("/cast Living Flame") }, { S("/cast [mod:alt] Dragonrage"), S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Pyre"), S("/cast Living Flame") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n", nil), mkRotation({ S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Disintegrate"), S("/cast Living Flame") }, { S("/cast Fire Breath"), S("/cast Eternity Surge"), S("/cast Pyre"), S("/cast Living Flame") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n", nil)))

-- EVOKER_1473
data["EVOKER_1473"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Dream Breath"), S("/cast Reversion"), S("/cast Echo"), S("/cast Living Flame"), S("/cast Emerald Blossom") }, { S("/cast Dream Breath"), S("/cast Spiritbloom"), S("/cast Emerald Blossom"), S("/cast Reversion"), S("/cast Living Flame") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n/cast Time Dilation\n", { S("/cast Reversion"), S("/cast Echo"), S("/cast Living Flame"), S("/cast Dream Breath"), S("/cast Spiritbloom"), S("/cast Emerald Blossom") }), mkRotation({ S("/cast [mod:alt] Dream Breath"), S("/cast Reversion"), S("/cast Echo"), S("/cast Living Flame"), S("/cast Emerald Blossom") }, { S("/cast [mod:alt] Dream Breath"), S("/cast Spiritbloom"), S("/cast Emerald Blossom"), S("/cast Reversion"), S("/cast Living Flame") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n/cast Time Dilation\n", { S("/cast Reversion"), S("/cast Echo"), S("/cast Living Flame"), S("/cast Dream Breath"), S("/cast Spiritbloom"), S("/cast Emerald Blossom") }), mkRotation({ S("/cast Dream Breath"), S("/cast Reversion"), S("/cast Echo"), S("/cast Living Flame"), S("/cast Emerald Blossom") }, { S("/cast Dream Breath"), S("/cast Spiritbloom"), S("/cast Emerald Blossom"), S("/cast Reversion"), S("/cast Living Flame") }, "/cast [harm] Quell\n", "/cast Obsidian Scales\n/cast Time Dilation\n", { S("/cast Reversion"), S("/cast Echo"), S("/cast Living Flame"), S("/cast Dream Breath"), S("/cast Spiritbloom"), S("/cast Emerald Blossom") })))

-- HUNTER_253
data["HUNTER_253"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Bestial Wrath"), S("/cast Barbed Shot"), S("/cast Kill Command"), S("/cast Cobra Shot"), S("/cast Kill Shot") }, { S("/cast Bestial Wrath"), S("/cast Barbed Shot"), S("/cast Multi-Shot"), S("/cast Kill Command"), S("/cast Cobra Shot") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil), mkRotation({ S("/cast [mod:alt] Bestial Wrath"), S("/cast Barbed Shot"), S("/cast Kill Command"), S("/cast Cobra Shot"), S("/cast Kill Shot") }, { S("/cast [mod:alt] Bestial Wrath"), S("/cast Barbed Shot"), S("/cast Multi-Shot"), S("/cast Kill Command"), S("/cast Cobra Shot") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil), mkRotation({ S("/cast Barbed Shot"), S("/cast Kill Command"), S("/cast Cobra Shot"), S("/cast Kill Shot") }, { S("/cast Barbed Shot"), S("/cast Multi-Shot"), S("/cast Kill Command"), S("/cast Cobra Shot") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil)))

-- HUNTER_254
data["HUNTER_254"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Trueshot"), S("/cast Aimed Shot"), S("/cast Rapid Fire"), S("/cast Arcane Shot"), S("/cast Steady Shot") }, { S("/cast Trueshot"), S("/cast Volley"), S("/cast Multi-Shot"), S("/cast Rapid Fire"), S("/cast Aimed Shot"), S("/cast Steady Shot") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil), mkRotation({ S("/cast [mod:alt] Trueshot"), S("/cast Aimed Shot"), S("/cast Rapid Fire"), S("/cast Arcane Shot"), S("/cast Steady Shot") }, { S("/cast [mod:alt] Trueshot"), S("/cast Volley"), S("/cast Multi-Shot"), S("/cast Rapid Fire"), S("/cast Aimed Shot"), S("/cast Steady Shot") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil), mkRotation({ S("/cast Aimed Shot"), S("/cast Rapid Fire"), S("/cast Arcane Shot"), S("/cast Steady Shot") }, { S("/cast Volley"), S("/cast Multi-Shot"), S("/cast Rapid Fire"), S("/cast Aimed Shot"), S("/cast Steady Shot") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil)))

-- HUNTER_255
data["HUNTER_255"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Coordinated Assault"), S("/cast Wildfire Bomb"), S("/cast Kill Command"), S("/cast Raptor Strike"), S("/cast Serpent Sting") }, { S("/cast Coordinated Assault"), S("/cast Wildfire Bomb"), S("/cast Carve"), S("/cast Butchery"), S("/cast Kill Command"), S("/cast Serpent Sting") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil), mkRotation({ S("/cast [mod:alt] Coordinated Assault"), S("/cast Wildfire Bomb"), S("/cast Kill Command"), S("/cast Raptor Strike"), S("/cast Serpent Sting") }, { S("/cast [mod:alt] Coordinated Assault"), S("/cast Wildfire Bomb"), S("/cast Carve"), S("/cast Butchery"), S("/cast Kill Command"), S("/cast Serpent Sting") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil), mkRotation({ S("/cast Wildfire Bomb"), S("/cast Kill Command"), S("/cast Raptor Strike"), S("/cast Serpent Sting") }, { S("/cast Wildfire Bomb"), S("/cast Carve"), S("/cast Butchery"), S("/cast Kill Command"), S("/cast Serpent Sting") }, "/cast [harm] Counter Shot\n", "/cast Exhilaration\n", nil)))

-- MAGE_62
data["MAGE_62"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Arcane Power"), S("/cast Touch of the Magi"), S("/cast Arcane Blast"), S("/cast Arcane Barrage"), S("/cast Arcane Missiles") }, { S("/cast Arcane Power"), S("/cast Arcane Explosion"), S("/cast Arcane Barrage"), S("/cast Arcane Missiles"), S("/cast Arcane Blast") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil), mkRotation({ S("/cast [mod:alt] Arcane Power"), S("/cast Touch of the Magi"), S("/cast Arcane Blast"), S("/cast Arcane Barrage"), S("/cast Arcane Missiles") }, { S("/cast [mod:alt] Arcane Power"), S("/cast Arcane Explosion"), S("/cast Arcane Barrage"), S("/cast Arcane Missiles"), S("/cast Arcane Blast") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil), mkRotation({ S("/cast Touch of the Magi"), S("/cast Arcane Blast"), S("/cast Arcane Barrage"), S("/cast Arcane Missiles") }, { S("/cast Arcane Explosion"), S("/cast Arcane Barrage"), S("/cast Arcane Missiles"), S("/cast Arcane Blast") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil)))

-- MAGE_63
data["MAGE_63"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Combustion"), S("/cast Fire Blast"), S("/cast Pyroblast"), S("/cast Fireball"), S("/cast Scorch") }, { S("/cast Combustion"), S("/cast Flamestrike"), S("/cast Fire Blast"), S("/cast Pyroblast"), S("/cast Fireball") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil), mkRotation({ S("/cast [mod:alt] Combustion"), S("/cast Fire Blast"), S("/cast Pyroblast"), S("/cast Fireball"), S("/cast Scorch") }, { S("/cast [mod:alt] Combustion"), S("/cast Flamestrike"), S("/cast Fire Blast"), S("/cast Pyroblast"), S("/cast Fireball") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil), mkRotation({ S("/cast Fire Blast"), S("/cast Pyroblast"), S("/cast Fireball"), S("/cast Scorch") }, { S("/cast Flamestrike"), S("/cast Fire Blast"), S("/cast Pyroblast"), S("/cast Fireball") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil)))

-- MAGE_64
data["MAGE_64"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Icy Veins"), S("/cast Frozen Orb"), S("/cast Blizzard"), S("/cast Ice Lance"), S("/cast Frostbolt") }, { S("/cast Icy Veins"), S("/cast Frozen Orb"), S("/cast Blizzard"), S("/cast Ice Lance"), S("/cast Frostbolt") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil), mkRotation({ S("/cast [mod:alt] Icy Veins"), S("/cast Frozen Orb"), S("/cast Blizzard"), S("/cast Ice Lance"), S("/cast Frostbolt") }, { S("/cast [mod:alt] Icy Veins"), S("/cast Frozen Orb"), S("/cast Blizzard"), S("/cast Ice Lance"), S("/cast Frostbolt") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil), mkRotation({ S("/cast Frozen Orb"), S("/cast Blizzard"), S("/cast Ice Lance"), S("/cast Frostbolt") }, { S("/cast Frozen Orb"), S("/cast Blizzard"), S("/cast Ice Lance"), S("/cast Frostbolt") }, "/cast [harm] Counterspell\n", "/cast Ice Block\n/cast Ice Barrier\n", nil)))

-- MONK_268
data["MONK_268"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Celestial Brew"), S("/cast Keg Smash"), S("/cast Breath of Fire"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, { S("/cast Celestial Brew"), S("/cast Keg Smash"), S("/cast Breath of Fire"), S("/cast Spinning Crane Kick"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n/cast Dampen Harm\n", nil), mkRotation({ S("/cast [mod:alt] Celestial Brew"), S("/cast Keg Smash"), S("/cast Breath of Fire"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, { S("/cast [mod:alt] Celestial Brew"), S("/cast Keg Smash"), S("/cast Breath of Fire"), S("/cast Spinning Crane Kick"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n/cast Dampen Harm\n", nil), mkRotation({ S("/cast Celestial Brew"), S("/cast Keg Smash"), S("/cast Breath of Fire"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, { S("/cast Celestial Brew"), S("/cast Keg Smash"), S("/cast Breath of Fire"), S("/cast Spinning Crane Kick"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n/cast Dampen Harm\n", nil)))

-- MONK_269
data["MONK_269"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Storm, Earth, and Fire"), S("/cast Rising Sun Kick"), S("/cast Fists of Fury"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, { S("/cast Storm, Earth, and Fire"), S("/cast Fists of Fury"), S("/cast Spinning Crane Kick"), S("/cast Rising Sun Kick"), S("/cast Blackout Kick") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n", nil), mkRotation({ S("/cast [mod:alt] Storm, Earth, and Fire"), S("/cast Rising Sun Kick"), S("/cast Fists of Fury"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, { S("/cast [mod:alt] Storm, Earth, and Fire"), S("/cast Fists of Fury"), S("/cast Spinning Crane Kick"), S("/cast Rising Sun Kick"), S("/cast Blackout Kick") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n", nil), mkRotation({ S("/cast Rising Sun Kick"), S("/cast Fists of Fury"), S("/cast Blackout Kick"), S("/cast Tiger Palm") }, { S("/cast Fists of Fury"), S("/cast Spinning Crane Kick"), S("/cast Rising Sun Kick"), S("/cast Blackout Kick") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n", nil)))

-- MONK_270
data["MONK_270"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Renewing Mist"), S("/cast Enveloping Mist"), S("/cast Vivify"), S("/cast Soothing Mist"), S("/cast Essence Font") }, { S("/cast Revival"), S("/cast Essence Font"), S("/cast Vivify"), S("/cast Renewing Mist"), S("/cast Enveloping Mist") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n/cast Life Cocoon\n", { S("/cast Renewing Mist"), S("/cast Vivify"), S("/cast Enveloping Mist"), S("/cast Essence Font"), S("/cast Life Cocoon") }), mkRotation({ S("/cast [mod:alt] Renewing Mist"), S("/cast Enveloping Mist"), S("/cast Vivify"), S("/cast Soothing Mist"), S("/cast Essence Font") }, { S("/cast [mod:alt] Revival"), S("/cast Essence Font"), S("/cast Vivify"), S("/cast Renewing Mist"), S("/cast Enveloping Mist") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n/cast Life Cocoon\n", { S("/cast Renewing Mist"), S("/cast Vivify"), S("/cast Enveloping Mist"), S("/cast Essence Font"), S("/cast Life Cocoon") }), mkRotation({ S("/cast Renewing Mist"), S("/cast Enveloping Mist"), S("/cast Vivify"), S("/cast Soothing Mist"), S("/cast Essence Font") }, { S("/cast Essence Font"), S("/cast Vivify"), S("/cast Renewing Mist"), S("/cast Enveloping Mist") }, "/cast [harm] Spear Hand Strike\n", "/cast Fortifying Brew\n/cast Life Cocoon\n", { S("/cast Renewing Mist"), S("/cast Vivify"), S("/cast Enveloping Mist"), S("/cast Essence Font"), S("/cast Life Cocoon") })))

-- PALADIN_65
data["PALADIN_65"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Light of Dawn"), S("/cast Flash of Light"), S("/cast Holy Light") }, { S("/cast Avenging Wrath"), S("/cast Light of Dawn"), S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Holy Light") }, "/cast [harm] Rebuke\n", "/cast Divine Shield\n/cast Blessing of Protection\n", { S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Light of Dawn"), S("/cast Flash of Light"), S("/cast Holy Light") }), mkRotation({ S("/cast [mod:alt] Holy Shock"), S("/cast Word of Glory"), S("/cast Light of Dawn"), S("/cast Flash of Light"), S("/cast Holy Light") }, { S("/cast [mod:alt] Avenging Wrath"), S("/cast Light of Dawn"), S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Holy Light") }, "/cast [harm] Rebuke\n", "/cast Divine Shield\n/cast Blessing of Protection\n", { S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Light of Dawn"), S("/cast Flash of Light"), S("/cast Holy Light") }), mkRotation({ S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Light of Dawn"), S("/cast Flash of Light"), S("/cast Holy Light") }, { S("/cast Light of Dawn"), S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Holy Light") }, "/cast [harm] Rebuke\n", "/cast Divine Shield\n/cast Blessing of Protection\n", { S("/cast Holy Shock"), S("/cast Word of Glory"), S("/cast Light of Dawn"), S("/cast Flash of Light"), S("/cast Holy Light") })))

-- PALADIN_66
data["PALADIN_66"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Avenging Wrath"), S("/cast Shield of the Righteous"), S("/cast Judgment"), S("/cast Avenger's Shield"), S("/cast Hammer of the Righteous") }, { S("/cast Avenging Wrath"), S("/cast Consecration"), S("/cast Avenger's Shield"), S("/cast Shield of the Righteous"), S("/cast Judgment"), S("/cast Hammer of the Righteous") }, "/cast [harm] Rebuke\n", "/cast Guardian of Ancient Kings\n/cast Ardent Defender\n", nil), mkRotation({ S("/cast [mod:alt] Avenging Wrath"), S("/cast Shield of the Righteous"), S("/cast Judgment"), S("/cast Avenger's Shield"), S("/cast Hammer of the Righteous") }, { S("/cast [mod:alt] Avenging Wrath"), S("/cast Consecration"), S("/cast Avenger's Shield"), S("/cast Shield of the Righteous"), S("/cast Judgment"), S("/cast Hammer of the Righteous") }, "/cast [harm] Rebuke\n", "/cast Guardian of Ancient Kings\n/cast Ardent Defender\n", nil), mkRotation({ S("/cast Shield of the Righteous"), S("/cast Judgment"), S("/cast Avenger's Shield"), S("/cast Hammer of the Righteous") }, { S("/cast Consecration"), S("/cast Avenger's Shield"), S("/cast Shield of the Righteous"), S("/cast Judgment"), S("/cast Hammer of the Righteous") }, "/cast [harm] Rebuke\n", "/cast Guardian of Ancient Kings\n/cast Ardent Defender\n", nil)))

-- PALADIN_70
data["PALADIN_70"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Avenging Wrath"), S("/cast Templar's Verdict"), S("/cast Blade of Justice"), S("/cast Judgment"), S("/cast Crusader Strike") }, { S("/cast Avenging Wrath"), S("/cast Divine Storm"), S("/cast Wake of Ashes"), S("/cast Blade of Justice"), S("/cast Judgment"), S("/cast Crusader Strike") }, "/cast [harm] Rebuke\n", "/cast Shield of Vengeance\n/cast Lay on Hands\n", nil), mkRotation({ S("/cast [mod:alt] Avenging Wrath"), S("/cast Templar's Verdict"), S("/cast Blade of Justice"), S("/cast Judgment"), S("/cast Crusader Strike") }, { S("/cast [mod:alt] Avenging Wrath"), S("/cast Divine Storm"), S("/cast Wake of Ashes"), S("/cast Blade of Justice"), S("/cast Judgment"), S("/cast Crusader Strike") }, "/cast [harm] Rebuke\n", "/cast Shield of Vengeance\n/cast Lay on Hands\n", nil), mkRotation({ S("/cast Templar's Verdict"), S("/cast Blade of Justice"), S("/cast Judgment"), S("/cast Crusader Strike") }, { S("/cast Divine Storm"), S("/cast Wake of Ashes"), S("/cast Blade of Justice"), S("/cast Judgment"), S("/cast Crusader Strike") }, "/cast [harm] Rebuke\n", "/cast Shield of Vengeance\n/cast Lay on Hands\n", nil)))

-- PRIEST_256
data["PRIEST_256"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Power Word: Radiance"), S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Flash Heal"), S("/cast Smite") }, { S("/cast Rapture"), S("/cast Power Word: Radiance"), S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Prayer of Healing") }, "/cast [harm] Silence\n", "/cast Pain Suppression\n/cast Power Word: Barrier\n", { S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Flash Heal"), S("/cast Power Word: Radiance"), S("/cast Prayer of Healing") }), mkRotation({ S("/cast [mod:alt] Power Word: Radiance"), S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Flash Heal"), S("/cast Smite") }, { S("/cast [mod:alt] Rapture"), S("/cast Power Word: Radiance"), S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Prayer of Healing") }, "/cast [harm] Silence\n", "/cast Pain Suppression\n/cast Power Word: Barrier\n", { S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Flash Heal"), S("/cast Power Word: Radiance"), S("/cast Prayer of Healing") }), mkRotation({ S("/cast Power Word: Radiance"), S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Flash Heal"), S("/cast Smite") }, { S("/cast Power Word: Radiance"), S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Prayer of Healing") }, "/cast [harm] Silence\n", "/cast Pain Suppression\n/cast Power Word: Barrier\n", { S("/cast Power Word: Shield"), S("/cast Penance"), S("/cast Flash Heal"), S("/cast Power Word: Radiance"), S("/cast Prayer of Healing") })))

-- PRIEST_257
data["PRIEST_257"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Holy Word: Serenity"), S("/cast Prayer of Mending"), S("/cast Flash Heal"), S("/cast Heal"), S("/cast Holy Word: Sanctify") }, { S("/cast Divine Hymn"), S("/cast Holy Word: Sanctify"), S("/cast Prayer of Healing"), S("/cast Prayer of Mending"), S("/cast Flash Heal") }, "/cast [harm] Silence\n", "/cast Guardian Spirit\n/cast Symbol of Hope\n", { S("/cast Prayer of Mending"), S("/cast Flash Heal"), S("/cast Heal"), S("/cast Holy Word: Serenity"), S("/cast Holy Word: Sanctify") }), mkRotation({ S("/cast [mod:alt] Holy Word: Serenity"), S("/cast Prayer of Mending"), S("/cast Flash Heal"), S("/cast Heal"), S("/cast Holy Word: Sanctify") }, { S("/cast [mod:alt] Divine Hymn"), S("/cast Holy Word: Sanctify"), S("/cast Prayer of Healing"), S("/cast Prayer of Mending"), S("/cast Flash Heal") }, "/cast [harm] Silence\n", "/cast Guardian Spirit\n/cast Symbol of Hope\n", { S("/cast Prayer of Mending"), S("/cast Flash Heal"), S("/cast Heal"), S("/cast Holy Word: Serenity"), S("/cast Holy Word: Sanctify") }), mkRotation({ S("/cast Holy Word: Serenity"), S("/cast Prayer of Mending"), S("/cast Flash Heal"), S("/cast Heal"), S("/cast Holy Word: Sanctify") }, { S("/cast Holy Word: Sanctify"), S("/cast Prayer of Healing"), S("/cast Prayer of Mending"), S("/cast Flash Heal") }, "/cast [harm] Silence\n", "/cast Guardian Spirit\n/cast Symbol of Hope\n", { S("/cast Prayer of Mending"), S("/cast Flash Heal"), S("/cast Heal"), S("/cast Holy Word: Serenity"), S("/cast Holy Word: Sanctify") })))

-- PRIEST_258
data["PRIEST_258"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Void Eruption"), S("/cast Vampiric Touch"), S("/cast Shadow Word: Pain"), S("/cast Mind Blast"), S("/cast Devouring Plague"), S("/cast Mind Flay") }, { S("/cast Void Eruption"), S("/cast Shadow Crash"), S("/cast Vampiric Touch"), S("/cast Shadow Word: Pain"), S("/cast Mind Sear"), S("/cast Devouring Plague") }, "/cast [harm] Silence\n", "/cast Desperate Prayer\n", nil), mkRotation({ S("/cast [mod:alt] Void Eruption"), S("/cast Vampiric Touch"), S("/cast Shadow Word: Pain"), S("/cast Mind Blast"), S("/cast Devouring Plague"), S("/cast Mind Flay") }, { S("/cast [mod:alt] Void Eruption"), S("/cast Shadow Crash"), S("/cast Vampiric Touch"), S("/cast Shadow Word: Pain"), S("/cast Mind Sear"), S("/cast Devouring Plague") }, "/cast [harm] Silence\n", "/cast Desperate Prayer\n", nil), mkRotation({ S("/cast Vampiric Touch"), S("/cast Shadow Word: Pain"), S("/cast Mind Blast"), S("/cast Devouring Plague"), S("/cast Mind Flay") }, { S("/cast Shadow Crash"), S("/cast Vampiric Touch"), S("/cast Shadow Word: Pain"), S("/cast Mind Sear"), S("/cast Devouring Plague") }, "/cast [harm] Silence\n", "/cast Desperate Prayer\n", nil)))

-- ROGUE_259
data["ROGUE_259"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Deathmark"), S("/cast Mutilate"), S("/cast Rupture"), S("/cast Envenom"), S("/cast Garrote") }, { S("/cast Deathmark"), S("/cast Fan of Knives"), S("/cast Rupture"), S("/cast Envenom"), S("/cast Garrote") }, "/cast [harm] Kick\n", "/cast Evasion\n/cast Vanish\n", nil), mkRotation({ S("/cast [mod:alt] Deathmark"), S("/cast Mutilate"), S("/cast Rupture"), S("/cast Envenom"), S("/cast Garrote") }, { S("/cast [mod:alt] Deathmark"), S("/cast Fan of Knives"), S("/cast Rupture"), S("/cast Envenom"), S("/cast Garrote") }, "/cast [harm] Kick\n", "/cast Evasion\n/cast Vanish\n", nil), mkRotation({ S("/cast Deathmark"), S("/cast Mutilate"), S("/cast Rupture"), S("/cast Envenom"), S("/cast Garrote") }, { S("/cast Deathmark"), S("/cast Fan of Knives"), S("/cast Rupture"), S("/cast Envenom"), S("/cast Garrote") }, "/cast [harm] Kick\n", "/cast Evasion\n/cast Vanish\n", nil)))

-- ROGUE_260
data["ROGUE_260"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Adrenaline Rush"), S("/cast Sinister Strike"), S("/cast Between the Eyes"), S("/cast Dispatch"), S("/cast Pistol Shot") }, { S("/cast Adrenaline Rush"), S("/cast Blade Flurry"), S("/cast Sinister Strike"), S("/cast Pistol Shot"), S("/cast Dispatch") }, "/cast [harm] Kick\n", "/cast Cloak of Shadows\n/cast Evasion\n", nil), mkRotation({ S("/cast [mod:alt] Adrenaline Rush"), S("/cast Sinister Strike"), S("/cast Between the Eyes"), S("/cast Dispatch"), S("/cast Pistol Shot") }, { S("/cast [mod:alt] Adrenaline Rush"), S("/cast Blade Flurry"), S("/cast Sinister Strike"), S("/cast Pistol Shot"), S("/cast Dispatch") }, "/cast [harm] Kick\n", "/cast Cloak of Shadows\n/cast Evasion\n", nil), mkRotation({ S("/cast Adrenaline Rush"), S("/cast Sinister Strike"), S("/cast Between the Eyes"), S("/cast Dispatch"), S("/cast Pistol Shot") }, { S("/cast Adrenaline Rush"), S("/cast Blade Flurry"), S("/cast Sinister Strike"), S("/cast Pistol Shot"), S("/cast Dispatch") }, "/cast [harm] Kick\n", "/cast Cloak of Shadows\n/cast Evasion\n", nil)))

-- ROGUE_261
data["ROGUE_261"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Shadow Dance"), S("/cast Shadowstrike"), S("/cast Eviscerate"), S("/cast Backstab"), S("/cast Symbols of Death") }, { S("/cast Shadow Dance"), S("/cast Shuriken Storm"), S("/cast Black Powder"), S("/cast Shadowstrike"), S("/cast Eviscerate") }, "/cast [harm] Kick\n", "/cast Cloak of Shadows\n/cast Vanish\n", nil), mkRotation({ S("/cast [mod:alt] Shadow Dance"), S("/cast Shadowstrike"), S("/cast Eviscerate"), S("/cast Backstab"), S("/cast Symbols of Death") }, { S("/cast [mod:alt] Shadow Dance"), S("/cast Shuriken Storm"), S("/cast Black Powder"), S("/cast Shadowstrike"), S("/cast Eviscerate") }, "/cast [harm] Kick\n", "/cast Cloak of Shadows\n/cast Vanish\n", nil), mkRotation({ S("/cast Shadow Dance"), S("/cast Shadowstrike"), S("/cast Eviscerate"), S("/cast Backstab"), S("/cast Symbols of Death") }, { S("/cast Shadow Dance"), S("/cast Shuriken Storm"), S("/cast Black Powder"), S("/cast Shadowstrike"), S("/cast Eviscerate") }, "/cast [harm] Kick\n", "/cast Cloak of Shadows\n/cast Vanish\n", nil)))

-- SHAMAN_262
data["SHAMAN_262"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Ascendance"), S("/cast Flame Shock"), S("/cast Lava Burst"), S("/cast Lightning Bolt"), S("/cast Earth Shock") }, { S("/cast Ascendance"), S("/cast Flame Shock"), S("/cast Chain Lightning"), S("/cast Earthquake"), S("/cast Lava Burst") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n", nil), mkRotation({ S("/cast [mod:alt] Ascendance"), S("/cast Flame Shock"), S("/cast Lava Burst"), S("/cast Lightning Bolt"), S("/cast Earth Shock") }, { S("/cast [mod:alt] Ascendance"), S("/cast Flame Shock"), S("/cast Chain Lightning"), S("/cast Earthquake"), S("/cast Lava Burst") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n", nil), mkRotation({ S("/cast Flame Shock"), S("/cast Lava Burst"), S("/cast Lightning Bolt"), S("/cast Earth Shock") }, { S("/cast Flame Shock"), S("/cast Chain Lightning"), S("/cast Earthquake"), S("/cast Lava Burst") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n", nil)))

-- SHAMAN_263
data["SHAMAN_263"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Feral Spirit"), S("/cast Stormstrike"), S("/cast Lava Lash"), S("/cast Lightning Bolt"), S("/cast Flame Shock") }, { S("/cast Feral Spirit"), S("/cast Crash Lightning"), S("/cast Stormstrike"), S("/cast Lava Lash"), S("/cast Chain Lightning") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n", nil), mkRotation({ S("/cast [mod:alt] Feral Spirit"), S("/cast Stormstrike"), S("/cast Lava Lash"), S("/cast Lightning Bolt"), S("/cast Flame Shock") }, { S("/cast [mod:alt] Feral Spirit"), S("/cast Crash Lightning"), S("/cast Stormstrike"), S("/cast Lava Lash"), S("/cast Chain Lightning") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n", nil), mkRotation({ S("/cast Stormstrike"), S("/cast Lava Lash"), S("/cast Lightning Bolt"), S("/cast Flame Shock") }, { S("/cast Crash Lightning"), S("/cast Stormstrike"), S("/cast Lava Lash"), S("/cast Chain Lightning") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n", nil)))

-- SHAMAN_264
data["SHAMAN_264"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Riptide"), S("/cast Healing Surge"), S("/cast Healing Wave"), S("/cast Chain Heal"), S("/cast Healing Rain") }, { S("/cast Healing Tide Totem"), S("/cast Healing Rain"), S("/cast Chain Heal"), S("/cast Riptide"), S("/cast Healing Surge") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n/cast Spirit Link Totem\n", { S("/cast Riptide"), S("/cast Healing Wave"), S("/cast Healing Surge"), S("/cast Chain Heal"), S("/cast Healing Rain") }), mkRotation({ S("/cast [mod:alt] Riptide"), S("/cast Healing Surge"), S("/cast Healing Wave"), S("/cast Chain Heal"), S("/cast Healing Rain") }, { S("/cast [mod:alt] Healing Tide Totem"), S("/cast Healing Rain"), S("/cast Chain Heal"), S("/cast Riptide"), S("/cast Healing Surge") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n/cast Spirit Link Totem\n", { S("/cast Riptide"), S("/cast Healing Wave"), S("/cast Healing Surge"), S("/cast Chain Heal"), S("/cast Healing Rain") }), mkRotation({ S("/cast Riptide"), S("/cast Healing Surge"), S("/cast Healing Wave"), S("/cast Chain Heal"), S("/cast Healing Rain") }, { S("/cast Healing Rain"), S("/cast Chain Heal"), S("/cast Riptide"), S("/cast Healing Surge") }, "/cast [harm] Wind Shear\n", "/cast Astral Shift\n/cast Spirit Link Totem\n", { S("/cast Riptide"), S("/cast Healing Wave"), S("/cast Healing Surge"), S("/cast Chain Heal"), S("/cast Healing Rain") })))

-- WARLOCK_265
data["WARLOCK_265"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Summon Darkglare"), S("/cast Unstable Affliction"), S("/cast Agony"), S("/cast Corruption"), S("/cast Malefic Rapture"), S("/cast Drain Soul") }, { S("/cast Summon Darkglare"), S("/cast Seed of Corruption"), S("/cast Agony"), S("/cast Corruption"), S("/cast Malefic Rapture"), S("/cast Drain Soul") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil), mkRotation({ S("/cast [mod:alt] Summon Darkglare"), S("/cast Unstable Affliction"), S("/cast Agony"), S("/cast Corruption"), S("/cast Malefic Rapture"), S("/cast Drain Soul") }, { S("/cast [mod:alt] Summon Darkglare"), S("/cast Seed of Corruption"), S("/cast Agony"), S("/cast Corruption"), S("/cast Malefic Rapture"), S("/cast Drain Soul") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil), mkRotation({ S("/cast Unstable Affliction"), S("/cast Agony"), S("/cast Corruption"), S("/cast Malefic Rapture"), S("/cast Drain Soul") }, { S("/cast Seed of Corruption"), S("/cast Agony"), S("/cast Corruption"), S("/cast Malefic Rapture"), S("/cast Drain Soul") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil)))

-- WARLOCK_266
data["WARLOCK_266"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Summon Demonic Tyrant"), S("/cast Call Dreadstalkers"), S("/cast Hand of Gul'dan"), S("/cast Demonbolt"), S("/cast Shadow Bolt") }, { S("/cast Summon Demonic Tyrant"), S("/cast Implosion"), S("/cast Hand of Gul'dan"), S("/cast Call Dreadstalkers"), S("/cast Shadow Bolt") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil), mkRotation({ S("/cast [mod:alt] Summon Demonic Tyrant"), S("/cast Call Dreadstalkers"), S("/cast Hand of Gul'dan"), S("/cast Demonbolt"), S("/cast Shadow Bolt") }, { S("/cast [mod:alt] Summon Demonic Tyrant"), S("/cast Implosion"), S("/cast Hand of Gul'dan"), S("/cast Call Dreadstalkers"), S("/cast Shadow Bolt") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil), mkRotation({ S("/cast Call Dreadstalkers"), S("/cast Hand of Gul'dan"), S("/cast Demonbolt"), S("/cast Shadow Bolt") }, { S("/cast Implosion"), S("/cast Hand of Gul'dan"), S("/cast Call Dreadstalkers"), S("/cast Shadow Bolt") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil)))

-- WARLOCK_267
data["WARLOCK_267"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Summon Infernal"), S("/cast Immolate"), S("/cast Conflagrate"), S("/cast Chaos Bolt"), S("/cast Incinerate") }, { S("/cast Summon Infernal"), S("/cast Immolate"), S("/cast Rain of Fire"), S("/cast Conflagrate"), S("/cast Incinerate") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil), mkRotation({ S("/cast [mod:alt] Summon Infernal"), S("/cast Immolate"), S("/cast Conflagrate"), S("/cast Chaos Bolt"), S("/cast Incinerate") }, { S("/cast [mod:alt] Summon Infernal"), S("/cast Immolate"), S("/cast Rain of Fire"), S("/cast Conflagrate"), S("/cast Incinerate") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil), mkRotation({ S("/cast Immolate"), S("/cast Conflagrate"), S("/cast Chaos Bolt"), S("/cast Incinerate") }, { S("/cast Immolate"), S("/cast Rain of Fire"), S("/cast Conflagrate"), S("/cast Incinerate") }, "/cast [harm] Spell Lock\n", "/cast Unending Resolve\n", nil)))

-- WARRIOR_71
data["WARRIOR_71"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Avatar"), S("/cast Overpower"), S("/cast Mortal Strike"), S("/cast Execute"), S("/cast Slam") }, { S("/cast Avatar"), S("/cast Bladestorm"), S("/cast Sweeping Strikes"), S("/cast Whirlwind"), S("/cast Mortal Strike") }, "/cast [harm] Pummel\n", "/cast Die by the Sword\n/cast Rallying Cry\n", nil), mkRotation({ S("/cast [mod:alt] Avatar"), S("/cast Overpower"), S("/cast Mortal Strike"), S("/cast Execute"), S("/cast Slam") }, { S("/cast [mod:alt] Avatar"), S("/cast Bladestorm"), S("/cast Sweeping Strikes"), S("/cast Whirlwind"), S("/cast Mortal Strike") }, "/cast [harm] Pummel\n", "/cast Die by the Sword\n/cast Rallying Cry\n", nil), mkRotation({ S("/cast Overpower"), S("/cast Mortal Strike"), S("/cast Execute"), S("/cast Slam") }, { S("/cast Bladestorm"), S("/cast Sweeping Strikes"), S("/cast Whirlwind"), S("/cast Mortal Strike") }, "/cast [harm] Pummel\n", "/cast Die by the Sword\n/cast Rallying Cry\n", nil)))

-- WARRIOR_72
data["WARRIOR_72"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Recklessness"), S("/cast Rampage"), S("/cast Raging Blow"), S("/cast Bloodthirst"), S("/cast Execute") }, { S("/cast Recklessness"), S("/cast Whirlwind"), S("/cast Rampage"), S("/cast Raging Blow"), S("/cast Bloodthirst") }, "/cast [harm] Pummel\n", "/cast Die by the Sword\n/cast Rallying Cry\n", nil), mkRotation({ S("/cast [mod:alt] Recklessness"), S("/cast Rampage"), S("/cast Raging Blow"), S("/cast Bloodthirst"), S("/cast Execute") }, { S("/cast [mod:alt] Recklessness"), S("/cast Whirlwind"), S("/cast Rampage"), S("/cast Raging Blow"), S("/cast Bloodthirst") }, "/cast [harm] Pummel\n", "/cast Die by the Sword\n/cast Rallying Cry\n", nil), mkRotation({ S("/cast Rampage"), S("/cast Raging Blow"), S("/cast Bloodthirst"), S("/cast Execute") }, { S("/cast Whirlwind"), S("/cast Rampage"), S("/cast Raging Blow"), S("/cast Bloodthirst") }, "/cast [harm] Pummel\n", "/cast Die by the Sword\n/cast Rallying Cry\n", nil)))

-- WARRIOR_73
data["WARRIOR_73"] = mkAllModes(mkProfiles(mkRotation({ S("/cast Avatar"), S("/cast Shield Block"), S("/cast Shield Slam"), S("/cast Revenge"), S("/cast Thunder Clap"), S("/cast Ignore Pain") }, { S("/cast Avatar"), S("/cast Thunder Clap"), S("/cast Revenge"), S("/cast Shield Slam"), S("/cast Shield Block"), S("/cast Ignore Pain") }, "/cast [harm] Pummel\n", "/cast Shield Wall\n/cast Last Stand\n", nil), mkRotation({ S("/cast [mod:alt] Avatar"), S("/cast Shield Block"), S("/cast Shield Slam"), S("/cast Revenge"), S("/cast Thunder Clap"), S("/cast Ignore Pain") }, { S("/cast [mod:alt] Avatar"), S("/cast Thunder Clap"), S("/cast Revenge"), S("/cast Shield Slam"), S("/cast Shield Block"), S("/cast Ignore Pain") }, "/cast [harm] Pummel\n", "/cast Shield Wall\n/cast Last Stand\n", nil), mkRotation({ S("/cast Shield Block"), S("/cast Shield Slam"), S("/cast Revenge"), S("/cast Thunder Clap"), S("/cast Ignore Pain") }, { S("/cast Thunder Clap"), S("/cast Revenge"), S("/cast Shield Slam"), S("/cast Shield Block"), S("/cast Ignore Pain") }, "/cast [harm] Pummel\n", "/cast Shield Wall\n/cast Last Stand\n", nil)))

return data