import json, sys, pathlib

def lua_str(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'

def dump_val(v, indent=2):
    if v is None: return "nil"
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    if isinstance(v, str): return lua_str(v)
    if isinstance(v, list):
        # Lua array
        parts = []
        for item in v:
            parts.append(" " * indent + dump_val(item, indent+2))
        return "{\n" + ",\n".join(parts) + "\n" + (" " * (indent-2)) + "}"
    if isinstance(v, dict):
        # Lua table
        parts = []
        # Sort keys for stability
        keys = sorted(v.keys())
        for k in keys:
            # Check if key is a valid identifier
            if k.replace('_','a').isalnum() and not k[0].isdigit():
                k_str = k
            else:
                k_str = f"[{lua_str(k)}]"
            
            parts.append(" " * indent + f"{k_str} = {dump_val(v[k], indent+2)}")
        return "{\n" + ",\n".join(parts) + "\n" + (" " * (indent-2)) + "}"
    return "nil"

def main():
    if len(sys.argv) < 3:
        print("Usage: python gen_defaults.py <rotations.json> <output_lua_path>")
        return

    in_path = sys.argv[1]
    out_path = sys.argv[2]

    try:
        with open(in_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading {in_path}: {e}")
        return

    # Structure of rotations.json is list of { specKey: "...", data: {...} }
    # OR dict { specKey: {...} } depending on cleanup.
    # RotationDump outputs a list.
    
    specs = {}
    if isinstance(data, list):
        for item in data:
            sk = item.get("specKey")
            sd = item.get("data")
            if sk and sd:
                specs[sk] = sd
    elif isinstance(data, dict):
        specs = data

    out_lines = []
    out_lines.append("-- rotations/defaults/AllSpecs.lua")
    out_lines.append("-- Auto-generated by tools/gen_defaults.py")
    out_lines.append("-- Contains offline-accessible default rotations.")
    out_lines.append("")
    out_lines.append("local data = {}")
    out_lines.append("")

    for specKey in sorted(specs.keys()):
        specData = specs[specKey]
        # Dump the table
        lua_table = dump_val(specData, 2)
        out_lines.append(f"data[{lua_str(specKey)}] = {lua_table}")
        out_lines.append("")

    out_lines.append("return data")

    try:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("\n".join(out_lines))
        print(f"Successfully generated {out_path} with {len(specs)} specs.")
    except Exception as e:
        print(f"Error writing {out_path}: {e}")

if __name__ == "__main__":
    main()
