-- core/Bindings.lua
-- Keybinding labels only (no runtime binding)

BINDING_HEADER_SKILLWEAVER = "SkillWeaver"

BINDING_NAME_SKILLWEAVER_ST   = "Single Target"
BINDING_NAME_SKILLWEAVER_AOE  = "Area of Effect"
BINDING_NAME_SKILLWEAVER_HEAL = "Heal (Smart)"
BINDING_NAME_SKILLWEAVER_SELF = "Self Save"
BINDING_NAME_SKILLWEAVER_INT  = "Interrupt"
BINDING_NAME_SKILLWEAVER_UTIL = "Utility"

BINDING_NAME_SKILLWEAVER_PRIMARY   = "Primary (Alias)"
BINDING_NAME_SKILLWEAVER_GROUPHEAL = "Group Heal (Alias)"
BINDING_NAME_SKILLWEAVER_TANKSAVE  = "Tank Save (Alias)"
BINDING_NAME_SKILLWEAVER_SELFSAVE  = "Self Save (Alias)"
