"""
Export Codex Data to Lua for DeepPockets addon.
Generates CodexData.lua containing quest coordinates and navigation targets.
"""

import sqlite3
import os

DB_FILE = "/Users/jgrayson/Documents/holocron/holocron.db"
ADDON_PATH = "/Users/jgrayson/Documents/holocron/HolocronViewer/CodexData.lua"

def get_db_connection():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn

def export_codex_data():
    print(f"Exporting Codex data to {ADDON_PATH}...")
    
    conn = get_db_connection()
    cur = conn.cursor()
    
    try:
        # Fetch all defined quests with coordinates
        cur.execute("""
            SELECT quest_id, title, x_coord, y_coord, map_id, area_name
            FROM quest_definitions
            WHERE x_coord IS NOT NULL AND y_coord IS NOT NULL AND map_id IS NOT NULL
        """)
        
        quests = cur.fetchall()
        
        with open(ADDON_PATH, "w") as f:
            f.write("-- Generated by Holocron Codex Engine\n")
            f.write("CodexDB = CodexDB or {}\n")
            f.write("CodexDB.QuestCoords = {\n")
            
            for q in quests:
                # Lua format: [QuestID] = { mapID = 123, x = 0.5, y = 0.5, title = "Name" },
                # Normalize coords to 0-1 if they are 0-100
                x = q['x_coord']
                y = q['y_coord']
                if x > 1: x = x / 100.0
                if y > 1: y = y / 100.0
                
                f.write(f"    [{q['quest_id']}] = {{ mapID = {q['map_id']}, x = {x:.4f}, y = {y:.4f}, title = \"{q['title']}\" }},\n")
                
            f.write("}\n")
            
        print(f"✓ Exported coordinates for {len(quests)} quests")
        
    except Exception as e:
        print(f"❌ Error exporting Codex data: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    export_codex_data()
